// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZySQv8VSIUJd5-saTBXZIwgtC_ugyURc',
    appId: '1:130279581505:web:35a11edb30cb8e0a5863c0',
    messagingSenderId: '130279581505',
    projectId: 'guardtrack-8e549',
    authDomain: 'guardtrack-8e549.firebaseapp.com',
    storageBucket: 'guardtrack-8e549.firebasestorage.app',
    measurementId: 'G-4EH53HBJFN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBM6tcADstNX0lk4rQ_V0Fgf510udX9FBg',
    appId: '1:130279581505:android:9cf8c016fc9589e75863c0',
    messagingSenderId: '130279581505',
    projectId: 'guardtrack-8e549',
    storageBucket: 'guardtrack-8e549.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvUYZfktz22xCSHVM8xolWOQ2AJy-PskI',
    appId: '1:130279581505:ios:526b5f7243308bd15863c0',
    messagingSenderId: '130279581505',
    projectId: 'guardtrack-8e549',
    storageBucket: 'guardtrack-8e549.firebasestorage.app',
    iosBundleId: 'com.example.guardtrackApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvUYZfktz22xCSHVM8xolWOQ2AJy-PskI',
    appId: '1:130279581505:ios:526b5f7243308bd15863c0',
    messagingSenderId: '130279581505',
    projectId: 'guardtrack-8e549',
    storageBucket: 'guardtrack-8e549.firebasestorage.app',
    iosBundleId: 'com.example.guardtrackApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZySQv8VSIUJd5-saTBXZIwgtC_ugyURc',
    appId: '1:130279581505:web:4824bd1e32604b435863c0',
    messagingSenderId: '130279581505',
    projectId: 'guardtrack-8e549',
    authDomain: 'guardtrack-8e549.firebaseapp.com',
    storageBucket: 'guardtrack-8e549.firebasestorage.app',
    measurementId: 'G-D2FFTHNPHJ',
  );

}